### ISSUE TITLE
AVR - GPIO

### ISSUE THREAD

**Issue by leandroschwarz** [leandroschwarz/gpdseLib#19]

**Comment by mayaradesousa** [comment]
1. Definição dos Registradores e Bit relacionados ao periférico;
    - [ ] PULL-UP
    - [ ] PORT_A
    - [ ] PORT_B
    - [ ] PORT_C
    - [ ] PORT_D
    - [ ] PORT_E
    - [ ] PORT_F
    - [ ] PORT_G
    - [ ] PORT_H
    - [ ] PORT_J

    - [ ] PORT_K
    - [ ] PORT_L
